from trp_env.envs.ant_trp_env import AntTwoResourceEnv, AntSmallTwoResourceEnv
from trp_env.envs.low_gear_ant_trp_env import LowGearAntTwoResourceEnv, LowGearAntSmallTwoResourceEnv
from trp_env.envs.snake_trp_env import SnakeTwoResourceEnv, SnakeSmallTwoResourceEnv
from trp_env.envs.swimmer_trp_env import SwimmerTwoResourceEnv, SwimmerSmallTwoResourceEnv
from trp_env.envs.humanoid_trp_env import HumanoidTwoResourceEnv, HumanoidSmallTwoResourceEnv
from trp_env.envs.realant_trp_env import RealAntTwoResourceEnv, RealAntSmallTwoResourceEnv
from trp_env.envs.wheel_trp_env import WheelTwoResourceEnv, WheelSmallTwoResourceEnv
from trp_env.envs.ball_trp_env import BallTwoResourceEnv, BallSmallTwoResourceEnv
